#!/usr/bin/env bash
# This script manages its own PID file and handles signals
echo $$ > /tmp/myscript.pid

trap "echo 'I hate the kill command'; rm /tmp/myscript.pid; exit" SIGTERM
trap "echo 'Y U no love me?!'; exit" SIGINT
trap "rm /tmp/myscript.pid; exit" SIGQUIT

while true; do
    echo "To infinity and beyond"
    sleep 1
done
